<?php

  function bethel_location_library_info() {
    $libraries['location-admin'] = array(
      'version' => \Drupal::VERSION,
      'js' => array(
        libraries_get_path('handlebars') . '/handlebars-1.1.2.js' => array('group' => JS_THEME),
        libraries_get_path('ember') . '/ember-1.3.1.js' => array('group' => JS_THEME),
        libraries_get_path('ember') . '/ember-data.min.js' => array('group' => JS_THEME),
        drupal_get_path('module', 'bethel_location') . '/js/app.js' => array('group' => JS_THEME),
        'http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false',
      ),
    );
    return $libraries;
  }
